### ISSUE TITLE
I find your code incomplete

### ISSUE THREAD

**Issue by ixmu** [bsbudhwar/Freeradius-Module-WHMCS#1]
Hello, my friend. I'm from the original developer.

I downloaded your code and found it incomplete.

![radius-2.png](https://i.loli.net/2020/11/02/lkeUSWCiTB7KvLd.png)
![radius-1.png](https://i.loli.net/2020/11/02/QAURX5x6MdaF3TS.png)
![radius-4.png](https://i.loli.net/2020/11/02/59sem2PogDKIVxA.png)
![radius-3.png](https://i.loli.net/2020/11/02/MRj5JguaeDFbLI8.png)

**Comment by bsbudhwar** [comment]
Hi this is just a sample original code is in private repository...

**Comment by heiye12** [comment]
Can I buy the complete code?   What is the price？

**Comment by heiye12** [comment]
> Hi this is just a sample original code is in private repository...



> Hi this is just a sample original code is in private repository...

Can I buy the complete code? What is the price？

**Comment by bsbudhwar** [comment]
Yes you can buy the code and code is not encrypted and cost is 120 USD one time.

**Comment by heiye12** [comment]
OK, I see. But I have three questions about the customer center product interface:
1. Does the module support Chinese?
2. Does the module support traffic reset?
3. module supports changing to any IP address in the product interface (_I do ocserv anyconnect VPN business to mainland China, because VPN's connection address is useful for forwarding other nodes, so the need to specify the connection address)

Sorry for my bad English，Please try to understand.

**Comment by heiye12** [comment]
OK, I see. But I have three questions about the customer center product interface:

1.Does the module support Chinese?
2.Does the module support traffic reset?
3.Does the module supports changing to any IP address in the product interface (_I do ocserv anyconnect VPN business to mainland China, because VPN's connection address is useful for forwarding other nodes, so the need to specify the connection address)

Sorry for my bad English，Please try to understand.

**Comment by bsbudhwar** [comment]
Hi, 

1. For Chinese version you can add Chinese language string file under module directory currently module is in English only but you can manage it with chinese as source code is there in files only.
2. Yes it supports that as its based on monthly bases or quarterly bases depends on billing cycle.
3. My module is based on freeradius server and whatever the VPN server it should uses freeradius and this module validate the details from freeradius database.

Currently we developed full stack with PPTP on debian with freeradius support and it works perfectly on mobiles and Windows 10 OS and any other OS as well. you can use any VPN server with backend freeradius with different IPS the same will be allotted to user by system.

**Comment by heiye12** [comment]
Let me think about it. I'll contact you if I buy.

**Comment by bsbudhwar** [comment]
Okay no problem

**Comment by bsbudhwar** [comment]
Hi we have a 25% off promo code **246LJK3PXL** for (Winter) December 2020 for all software products.

**Comment by heiye12** [comment]
The verification method of ocserv anyconnect vpn is ip:port user passwd, I'm thinking about how to sell automatically，Because there is no "port" in the product interface

**Comment by bsbudhwar** [comment]
Port is standard in VPN servers are you using any customised VPN server like IPSec, pptpd, and l2tpd etc are standard VPN servers which don't required any special ports and IP's are automatically assigned by VPN server's DHCP servers.

For port you can customise the source code as code is available and what about IP are you assign IP's to your customers...? Or by VPN server.
